name: Build Installer for PD 3.0
on: 
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-win-executable-for-PD-3.0:
    runs-on: windows-latest

    env:
      PYTHON_VERSION: 3.11.9
      Installer_NAME: PDNuXLNode_3.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4



